version: "1.0"
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:1.10.11
    container_name: selenoid
    volumes:
      - ./config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/video:/opt/selenoid/video
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/dev/video
    ports:
      - "4444:4444"
  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.9
    network_mode: bridge
    links:
      - selenoid
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
volumes:
  target:
    driver: local
